### PR TITLE
Create en.json

### PR DESCRIPTION
**Pull request by Voxyd**

### CODE REVIEW

**Comment by Ne0blast** [comment]
I think there's some mistakes in the translation :)

- Page de garde : Flyleaf
- Projets privés : Private projects
- Projets publics : Public projects
- Tâches du jour : Today's tasks
- Tâches du lendemain : Tomorrow's tasks

Thanks for your concern about the project ;)

**Comment by Super-Baleine** [comment]
By the way, what "Page de garde" means ?

**Comment by Ne0blast** [comment]
A flyleaf is a presentation page of a document : [https://www.qwant.com/?q=page+de+garde&client=qwantfirefox](https://www.qwant.com/?q=page+de+garde&client=qwantfirefox)

**Comment by Super-Baleine** [comment]
I think you should keep open the PR and wait the modifications, nope ?

**Comment by Ne0blast** [comment]
I've done it myself. I'll add it for the next push :)

Thanks to Voxyd for his concern ;)

**Comment by Super-Baleine** [comment]
xD
you're so wicked xD

**Pull request closed without merging**
